//! Hugging Face model directory import — the whole repo, not just the weights.
//!
//! `docs/design/import-export.md` §3 lists "Hugging Face repo" as its own row,
//! and the reason it is a row rather than a footnote on safetensors is that a
//! model on the hub is five files that only mean something together:
//!
//! | file | what it carries | where it lands |
//! |---|---|---|
//! | `model*.safetensors` / `pytorch_model*.bin` | the weights | §04 tensors |
//! | `config.json` | architecture parameters | §06.2 `arch` |
//! | `tokenizer.json` | the tokenizer | §06.7 `omni.tok/tokenizer` |
//! | `tokenizer_config.json` | the chat template | §06.9 OMNI-CT |
//! | `generation_config.json` | decoding defaults | §06.6 |
//!
//! Importing them one at a time produces five containers that do not know about
//! each other. Importing them together produces the thing OMNI is for: one
//! content-addressed artifact where the tokenizer that was shipped with these
//! weights is *in* the file, addressed by digest, rather than being a second
//! download that might not match.
//!
//! ## What this importer will not do
//!
//! It will not invent. `config.json` has no license field, so no license is
//! written. HF's config does not state RoPE's pairing convention — the
//! `interleaved` flag of §06.3, which the specification calls out as the field
//! that "has caused more silent output corruption in format conversions than
//! any other" — so it is written only for the model families where the
//! `transformers` implementation is unambiguous, and named as an assumption
//! when it is.
//!
//! It will not claim a tokenizer it cannot run. Every normalizer, pre-tokenizer
//! and decoder step outside §06.7's catalogue is imported as `unsupported` with
//! its own name, so `omni verify --tokenizer` reports *indeterminate* rather
//! than producing ids that are wrong in a way nobody notices.
//!
//! And it produces **no conformance vectors** (§06.7.1). Vectors have to come
//! from the source tokenizer, and this importer cannot run `tokenizers`; a
//! vector generated by the encoder it is supposed to test cannot fail. The
//! absence is recorded in the fidelity report rather than papered over.

use crate::cbor::Value;
use crate::container::{otype, Object};
use crate::json;
use crate::model::ModelBuilder;
use crate::safetensors::{Fidelity, Imported, Note};

pub const IMPORTER: &str = "omni-core/hf";

#[derive(Debug)]
pub enum Error {
    /// A file that has to be there is not.
    Missing(String),
    /// A file is there and is not what it claims to be.
    Malformed(String),
    /// Well formed, and this build cannot represent it.
    Unsupported(String),
    Core(String),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Missing(m) => write!(f, "{m}"),
            Error::Malformed(m) => write!(f, "malformed: {m}"),
            Error::Unsupported(m) => write!(f, "unsupported: {m}"),
            Error::Core(m) => write!(f, "{m}"),
        }
    }
}
impl std::error::Error for Error {}

pub type Res<T> = Result<T, Error>;

/// How a weight shard is encoded.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Weights {
    Safetensors,
    PyTorch,
}

pub struct Shard {
    pub name: String,
    pub kind: Weights,
    pub bytes: Vec<u8>,
}

/// The directory, already read. The core crate stays out of the filesystem;
/// the CLI finds the files and this decides what they mean.
#[derive(Default)]
pub struct Files {
    pub config: Option<Vec<u8>>,
    pub tokenizer: Option<Vec<u8>>,
    pub tokenizer_config: Option<Vec<u8>>,
    pub generation_config: Option<Vec<u8>>,
    /// Shards in load order. A sharded checkpoint's `*.index.json` decides that
    /// order; a single file is its own.
    pub shards: Vec<Shard>,
}

pub struct ImportOpts {
    pub name: String,
    pub source_path: String,
    pub hash: crate::container::HashAlgo,
    pub chunk_size: usize,
    pub license: Option<String>,
}

impl Default for ImportOpts {
    fn default() -> Self {
        ImportOpts {
            name: "imported/hf".into(),
            source_path: String::new(),
            hash: crate::container::HashAlgo::default(),
            chunk_size: 1 << 20,
            license: None,
        }
    }
}

// ------------------------------------------------------------------- config --

/// `config.json` keys with a §06.2 spelling. Everything else is kept under
/// `hf`, so nothing is lost and nothing is ambiguous about which name it had.
const CONFIG_MAP: &[(&str, &str)] = &[
    ("hidden_size", "hidden_size"),
    ("num_hidden_layers", "n_layers"),
    ("num_attention_heads", "n_heads"),
    ("num_key_value_heads", "n_kv_heads"),
    ("head_dim", "head_dim"),
    ("intermediate_size", "ffn_hidden"),
    ("hidden_act", "activation"),
    ("max_position_embeddings", "n_ctx"),
    ("vocab_size", "vocab_size"),
];

/// Model families whose `transformers` implementation rotates RoPE in
/// NeoX pairing — halves, not adjacent pairs. §06.3 requires `interleaved`
/// when `kind` is `rope`, and this is the only honest way to supply it: from
/// knowledge of the implementation, recorded as an assumption, for families
/// where there is no ambiguity. An unlisted family gets no `rope` block at all.
const NEOX_PAIRING: &[&str] = &[
    "llama",
    "mistral",
    "mixtral",
    "qwen2",
    "qwen3",
    "gemma",
    "gemma2",
    "phi3",
    "olmo",
    "starcoder2",
    "cohere",
    "granite",
];

fn jnum(v: &json::Value) -> Option<Value> {
    Some(match v {
        json::Value::U(u) => Value::U(*u),
        json::Value::I(i) => Value::I(*i),
        json::Value::F(f) => Value::F64(*f),
        _ => return None,
    })
}

fn to_cbor(v: &json::Value) -> Value {
    match v {
        json::Value::Null => Value::Null,
        json::Value::Bool(b) => Value::Bool(*b),
        json::Value::Str(s) => Value::text(s.clone()),
        json::Value::Array(a) => Value::Array(a.iter().map(to_cbor).collect()),
        json::Value::Object(m) => {
            Value::map(m.iter().map(|(k, x)| (k.as_str(), to_cbor(x))).collect())
        }
        other => jnum(other).unwrap_or(Value::Null),
    }
}

/// Reads `config.json` into a §06.2 architecture descriptor.
pub fn arch_of(cfg: &json::Value, notes: &mut Vec<Note>) -> (String, Vec<(String, Value)>) {
    let family = cfg
        .get("model_type")
        .and_then(|x| x.as_str())
        .unwrap_or("unknown")
        .to_string();
    let mut params: Vec<(String, Value)> = Vec::new();
    let mut mapped = std::collections::BTreeSet::new();
    for (hf, omni) in CONFIG_MAP {
        if let Some(v) = cfg.get(hf) {
            if let Some(c) = jnum(v).or_else(|| v.as_str().map(Value::text)) {
                params.push(((*omni).to_string(), c));
                mapped.insert(hf.to_string());
            }
        }
    }

    // §06.2's `norm` block, which HF spreads across two differently named keys
    // depending on the family.
    let eps = cfg
        .get("rms_norm_eps")
        .or_else(|| cfg.get("layer_norm_eps"))
        .or_else(|| cfg.get("layer_norm_epsilon"));
    if let Some(e) = eps.and_then(jnum) {
        let rms = cfg.get("rms_norm_eps").is_some();
        params.push((
            "norm".into(),
            Value::map(vec![
                (
                    "kind",
                    Value::text(if rms { "rmsnorm" } else { "layernorm" }),
                ),
                ("eps", e),
                // Every family in `transformers` that states one of these keys
                // normalizes before the sublayer.
                ("pre", Value::Bool(true)),
            ]),
        ));
        for k in ["rms_norm_eps", "layer_norm_eps", "layer_norm_epsilon"] {
            mapped.insert(k.to_string());
        }
    }

    // §06.3. `theta` is stated; `interleaved` never is.
    if let Some(theta) = cfg.get("rope_theta").and_then(jnum) {
        mapped.insert("rope_theta".into());
        if NEOX_PAIRING.contains(&family.as_str()) {
            let mut rope = vec![
                ("kind", Value::text("rope")),
                ("theta", theta),
                ("interleaved", Value::Bool(false)),
            ];
            if let Some(scaling) = cfg.get("rope_scaling") {
                mapped.insert("rope_scaling".into());
                if !matches!(scaling, json::Value::Null) {
                    rope.push(("scaling", to_cbor(scaling)));
                }
            }
            params.push(("rope".into(), Value::map(rope)));
            notes.push(Note {
                item: "rope.interleaved".into(),
                reason: "config.json never states RoPE's pairing convention, and §06.3 \
                         calls it the field that has caused the most silent corruption"
                    .into(),
                action: format!(
                    "written as `false` (NeoX halves) from the `transformers` \
                     implementation of `{family}`, not from the file"
                ),
            });
        } else {
            notes.push(Note {
                item: "rope".into(),
                reason: format!(
                    "`{family}` is not a family whose RoPE pairing this build knows, and \
                     §06.3 requires `interleaved` when `kind` is `rope`"
                ),
                action: "no rope block written; `rope_theta` is kept under `hf`".into(),
            });
            mapped.remove("rope_theta");
        }
    }

    if let Some(json::Value::Bool(t)) = cfg.get("tie_word_embeddings") {
        params.push(("tie_embeddings".into(), Value::Bool(*t)));
        mapped.insert("tie_word_embeddings".into());
    }

    // Everything else, verbatim, under its own name. `arch.params` is
    // explicitly free-form (§06.2), so keeping the file's own keys costs
    // nothing and loses nothing.
    if let json::Value::Object(m) = cfg {
        let rest: Vec<(&str, Value)> = m
            .iter()
            .filter(|(k, _)| !mapped.contains(*k) && *k != "model_type")
            .map(|(k, v)| (k.as_str(), to_cbor(v)))
            .collect();
        if !rest.is_empty() {
            params.push(("hf".into(), Value::map(rest)));
        }
    }
    (family, params)
}

// ---------------------------------------------------------------- tokenizer --

/// The §06.7 tokenizer, read out of `tokenizer.json`.
pub struct TokenizerParts {
    pub kind: &'static str,
    pub tokens: Vec<String>,
    pub scores: Vec<f32>,
    /// Merges as id pairs (§06.7), not strings.
    pub merges: Vec<(u32, u32)>,
    pub normalizers: Vec<Value>,
    pub pretokenizers: Vec<Value>,
    pub decoder: Vec<Value>,
    pub added: Vec<Value>,
    pub byte_fallback: bool,
    pub unk: Option<u32>,
    pub post_single: Vec<String>,
}

fn step(kind: &str, extra: Vec<(&str, Value)>) -> Value {
    let mut p = vec![("k", Value::text(kind))];
    p.extend(extra);
    Value::map(p)
}

fn unsupported_step(name: &str) -> Value {
    step(name, vec![])
}

/// Flattens HF's `Sequence` wrappers, which nest the same shape at three
/// different key names.
fn sequence<'a>(v: &'a json::Value, key: &str) -> Vec<&'a json::Value> {
    match v.get("type").and_then(|x| x.as_str()) {
        Some("Sequence") => v
            .get(key)
            .and_then(|x| x.as_array())
            .map(|a| a.iter().collect())
            .unwrap_or_default(),
        Some(_) => vec![v],
        None => vec![],
    }
}

fn normalizer_of(n: &json::Value) -> Value {
    match n.get("type").and_then(|x| x.as_str()).unwrap_or("") {
        "NFC" => step("nfc", vec![]),
        "Lowercase" => step("lowercase", vec![]),
        "StripAccents" => step("strip-accents", vec![]),
        "Replace" => {
            let pattern = n
                .get("pattern")
                .and_then(|p| p.get("Regex").or_else(|| p.get("String")))
                .and_then(|x| x.as_str())
                .unwrap_or_default();
            step(
                "replace",
                vec![
                    ("pattern", Value::text(pattern)),
                    (
                        "to",
                        Value::text(n.get("content").and_then(|x| x.as_str()).unwrap_or("")),
                    ),
                ],
            )
        }
        // NFD, NFKC, NFKD, Prepend, Strip, BertNormalizer and the rest are real
        // and not implemented here. Naming them is what makes `omni verify
        // --tokenizer` say *indeterminate* instead of producing wrong ids.
        other => unsupported_step(&other.to_lowercase()),
    }
}

fn pretokenizer_of(p: &json::Value) -> Value {
    match p.get("type").and_then(|x| x.as_str()).unwrap_or("") {
        "ByteLevel" => step(
            "byte-level",
            vec![(
                "add_prefix_space",
                Value::Bool(matches!(
                    p.get("add_prefix_space"),
                    Some(json::Value::Bool(true))
                )),
            )],
        ),
        "Whitespace" | "WhitespaceSplit" => step("whitespace", vec![]),
        "Metaspace" => step(
            "metaspace",
            vec![
                (
                    "replacement",
                    Value::text(
                        p.get("replacement")
                            .and_then(|x| x.as_str())
                            .unwrap_or("\u{2581}"),
                    ),
                ),
                (
                    "prepend",
                    Value::Bool(!matches!(
                        p.get("prepend_scheme").and_then(|x| x.as_str()),
                        Some("never")
                    )),
                ),
            ],
        ),
        "Split" => {
            let pattern = p.get("pattern");
            let (re, flavor) = match pattern
                .and_then(|x| x.get("Regex"))
                .and_then(|x| x.as_str())
            {
                // HF's `Split` regexes are Rust `regex` crate syntax, and §06.7
                // is right that the flavor changes the ids. It is recorded
                // rather than assumed to be compatible.
                Some(re) => (re.to_string(), "rust-regex"),
                None => (
                    pattern
                        .and_then(|x| x.get("String"))
                        .and_then(|x| x.as_str())
                        .unwrap_or_default()
                        .to_string(),
                    "literal",
                ),
            };
            step(
                "regex-split",
                vec![
                    (
                        "pattern",
                        Value::map(vec![
                            ("re", Value::text(re)),
                            ("flavor", Value::text(flavor)),
                        ]),
                    ),
                    (
                        "behavior",
                        Value::text(
                            p.get("behavior")
                                .and_then(|x| x.as_str())
                                .unwrap_or("isolated")
                                .to_lowercase(),
                        ),
                    ),
                ],
            )
        }
        other => unsupported_step(&other.to_lowercase()),
    }
}

fn decoder_of(d: &json::Value) -> Value {
    match d.get("type").and_then(|x| x.as_str()).unwrap_or("") {
        "ByteLevel" => step("byte-level", vec![]),
        "Metaspace" => step(
            "metaspace",
            vec![(
                "replacement",
                Value::text(
                    d.get("replacement")
                        .and_then(|x| x.as_str())
                        .unwrap_or("\u{2581}"),
                ),
            )],
        ),
        "Replace" => step(
            "replace",
            vec![
                (
                    "pattern",
                    Value::text(
                        d.get("pattern")
                            .and_then(|p| p.get("Regex").or_else(|| p.get("String")))
                            .and_then(|x| x.as_str())
                            .unwrap_or_default(),
                    ),
                ),
                (
                    "to",
                    Value::text(d.get("content").and_then(|x| x.as_str()).unwrap_or("")),
                ),
            ],
        ),
        other => unsupported_step(&other.to_lowercase()),
    }
}

/// Reads `tokenizer.json`.
pub fn tokenizer_of(tj: &json::Value, notes: &mut Vec<Note>) -> Res<TokenizerParts> {
    let model = tj
        .get("model")
        .ok_or_else(|| Error::Malformed("tokenizer.json has no `model`".into()))?;
    let mtype = model.get("type").and_then(|x| x.as_str()).unwrap_or("");

    // The vocabulary, in id order. HF stores it as token → id, and the ids are
    // dense; a gap would mean the file disagrees with itself, so it is checked
    // rather than filled in.
    let mut tokens: Vec<String> = Vec::new();
    let mut scores: Vec<f32> = Vec::new();
    let kind = match mtype {
        "BPE" | "WordPiece" | "WordLevel" => {
            let vocab = model
                .get("vocab")
                .and_then(|x| x.as_object())
                .ok_or_else(|| Error::Malformed("the model has no `vocab` map".into()))?;
            let mut by_id: Vec<(u64, &String)> = vocab
                .iter()
                .filter_map(|(t, v)| v.as_u64().map(|i| (i, t)))
                .collect();
            by_id.sort_unstable();
            for (want, (got, t)) in by_id.iter().enumerate() {
                if *got != want as u64 {
                    return Err(Error::Malformed(format!(
                        "the vocabulary skips id {want}; `{t}` claims {got}"
                    )));
                }
                tokens.push((*t).clone());
            }
            match mtype {
                "BPE" => "bpe",
                "WordPiece" => "wordpiece",
                _ => "wordlevel",
            }
        }
        "Unigram" => {
            let v = model
                .get("vocab")
                .and_then(|x| x.as_array())
                .ok_or_else(|| Error::Malformed("Unigram has no `vocab` array".into()))?;
            for e in v {
                let a = e
                    .as_array()
                    .ok_or_else(|| Error::Malformed("a Unigram entry is not a pair".into()))?;
                tokens.push(
                    a.first()
                        .and_then(|x| x.as_str())
                        .ok_or_else(|| Error::Malformed("a Unigram token is not text".into()))?
                        .to_string(),
                );
                scores.push(match a.get(1) {
                    Some(json::Value::F(f)) => *f as f32,
                    Some(json::Value::I(i)) => *i as f32,
                    Some(json::Value::U(u)) => *u as f32,
                    _ => 0.0,
                });
            }
            "unigram"
        }
        other => {
            return Err(Error::Unsupported(format!(
                "tokenizer model `{other}`; §06.7's catalogue has bpe, unigram, wordpiece \
                 and wordlevel, and guessing which one this is would change every id"
            )))
        }
    };

    // Merges as id pairs. A merge naming a token the vocabulary lacks is an
    // error rather than a skipped line: it means the two halves of the file
    // disagree, and the ids would come out wrong.
    let index: std::collections::BTreeMap<String, u32> = tokens
        .iter()
        .enumerate()
        .map(|(i, t)| (t.clone(), i as u32))
        .collect();
    let mut merges = Vec::new();
    if let Some(ms) = model.get("merges").and_then(|x| x.as_array()) {
        for m in ms {
            // Two spellings in the wild: "a b" and ["a", "b"].
            let (l, r) = match m {
                json::Value::Str(s) => match s.split_once(' ') {
                    Some((l, r)) => (l.to_string(), r.to_string()),
                    None => {
                        return Err(Error::Malformed(format!("merge `{s}` is not a pair")));
                    }
                },
                json::Value::Array(a) if a.len() == 2 => (
                    a[0].as_str().unwrap_or_default().to_string(),
                    a[1].as_str().unwrap_or_default().to_string(),
                ),
                _ => {
                    return Err(Error::Malformed(
                        "a merge is neither text nor a pair".into(),
                    ))
                }
            };
            let (Some(li), Some(ri)) = (index.get(&l), index.get(&r)) else {
                return Err(Error::Malformed(format!(
                    "merge `{l} {r}` names a token the vocabulary does not contain"
                )));
            };
            merges.push((*li, *ri));
        }
    }

    let normalizers: Vec<Value> = tj
        .get("normalizer")
        .map(|n| {
            sequence(n, "normalizers")
                .iter()
                .map(|x| normalizer_of(x))
                .collect()
        })
        .unwrap_or_default();
    let pretokenizers: Vec<Value> = tj
        .get("pre_tokenizer")
        .map(|p| {
            sequence(p, "pretokenizers")
                .iter()
                .map(|x| pretokenizer_of(x))
                .collect()
        })
        .unwrap_or_default();
    let decoder: Vec<Value> = tj
        .get("decoder")
        .map(|d| {
            sequence(d, "decoders")
                .iter()
                .map(|x| decoder_of(x))
                .collect()
        })
        .unwrap_or_default();

    for (what, steps) in [
        ("normalizer", &normalizers),
        ("pre-tokenizer", &pretokenizers),
        ("decoder", &decoder),
    ] {
        for s in steps {
            let k = s.get("k").and_then(|x| x.as_str()).unwrap_or("");
            let known = matches!(
                (what, k),
                (
                    "normalizer",
                    "nfc" | "lowercase" | "strip-accents" | "replace"
                ) | (
                    "pre-tokenizer",
                    "byte-level" | "whitespace" | "regex-split" | "metaspace"
                ) | ("decoder", "byte-level" | "replace" | "metaspace")
            );
            if !known {
                notes.push(Note {
                    item: format!("{what} `{k}`"),
                    reason: "outside §06.7's catalogue".into(),
                    action: "carried by name; encoding with it is indeterminate, not wrong".into(),
                });
            }
        }
    }

    let mut added = Vec::new();
    for a in tj
        .get("added_tokens")
        .and_then(|x| x.as_array())
        .unwrap_or(&[])
    {
        added.push(Value::map(vec![
            (
                "id",
                Value::U(a.get("id").and_then(|x| x.as_u64()).unwrap_or(0)),
            ),
            (
                "content",
                Value::text(a.get("content").and_then(|x| x.as_str()).unwrap_or("")),
            ),
            (
                "special",
                Value::Bool(matches!(a.get("special"), Some(json::Value::Bool(true)))),
            ),
            (
                "lstrip",
                Value::Bool(matches!(a.get("lstrip"), Some(json::Value::Bool(true)))),
            ),
            (
                "rstrip",
                Value::Bool(matches!(a.get("rstrip"), Some(json::Value::Bool(true)))),
            ),
        ]));
    }

    // The post-processor, for the single-sequence case §06.7 models. A
    // `TemplateProcessing` `single` is a list of `SpecialToken` and `Sequence`
    // entries; only the special tokens are stored, in order, around `A`.
    let mut post_single = Vec::new();
    if let Some(pp) = tj.get("post_processor") {
        let procs = sequence(pp, "processors");
        for p in procs {
            match p.get("type").and_then(|x| x.as_str()) {
                Some("TemplateProcessing") => {
                    for e in p.get("single").and_then(|x| x.as_array()).unwrap_or(&[]) {
                        if let Some(t) = e.get("SpecialToken").and_then(|s| s.get("id")) {
                            if let Some(s) = t.as_str() {
                                post_single.push(s.to_string());
                            }
                        } else if e.get("Sequence").is_some() {
                            post_single.push("A".into());
                        }
                    }
                }
                Some("ByteLevel") | Some("RobertaProcessing") | Some("BertProcessing") => {
                    notes.push(Note {
                        item: "post_processor".into(),
                        reason: format!(
                            "`{}` is not the template form §06.7 models",
                            p.get("type").and_then(|x| x.as_str()).unwrap_or("?")
                        ),
                        action: "not written; the tokenizer encodes without it".into(),
                    });
                }
                _ => {}
            }
        }
    }

    Ok(TokenizerParts {
        kind,
        tokens,
        scores,
        merges,
        normalizers,
        pretokenizers,
        decoder,
        added,
        byte_fallback: matches!(model.get("byte_fallback"), Some(json::Value::Bool(true))),
        unk: model
            .get("unk_token")
            .and_then(|x| x.as_str())
            .and_then(|t| index.get(t).copied())
            .or_else(|| {
                model
                    .get("unk_id")
                    .and_then(|x| x.as_u64())
                    .map(|x| x as u32)
            }),
        post_single,
    })
}

/// Builds the `omni.tok/tokenizer` object, putting the vocabulary and the
/// merge table into tensors (§06.7) rather than inline CBOR — a 256 k
/// vocabulary is about 3 MB, and inline it would be read on every `inspect`.
fn tokenizer_asset(b: &mut ModelBuilder, t: &TokenizerParts) -> Value {
    use crate::dtype::DType;
    use crate::layout::Layout;

    let blob = crate::tokenizer::encode_vocab(&t.tokens);
    let vocab_expr = b.literal(
        &blob,
        DType::Str,
        &[t.tokens.len() as u64],
        Layout::default(),
    );
    let mut vocab = vec![("tokens", vocab_expr.to_value())];
    if !t.scores.is_empty() {
        let raw: Vec<u8> = t.scores.iter().flat_map(|s| s.to_le_bytes()).collect();
        let e = b.literal(
            &raw,
            DType::F32,
            &[t.scores.len() as u64],
            Layout::default(),
        );
        vocab.push(("scores", e.to_value()));
    }

    let mut fields = vec![
        ("t", Value::text("omni.tok/tokenizer")),
        ("v", Value::U(1)),
        ("kind", Value::text(t.kind)),
        ("vocab", Value::map(vocab)),
    ];
    if !t.merges.is_empty() {
        let raw: Vec<u8> = t
            .merges
            .iter()
            .flat_map(|(l, r)| [l.to_le_bytes(), r.to_le_bytes()])
            .flatten()
            .collect();
        let e = b.literal(
            &raw,
            DType::Int {
                w: 32,
                signed: false,
            },
            &[t.merges.len() as u64, 2],
            Layout::default(),
        );
        fields.push(("merges", e.to_value()));
    }
    if !t.normalizers.is_empty() {
        fields.push(("normalizers", Value::Array(t.normalizers.clone())));
    }
    if !t.pretokenizers.is_empty() {
        fields.push(("pretokenizers", Value::Array(t.pretokenizers.clone())));
    }
    if !t.decoder.is_empty() {
        fields.push(("decoder", Value::Array(t.decoder.clone())));
    }
    if !t.added.is_empty() {
        fields.push(("added_tokens", Value::Array(t.added.clone())));
    }
    if t.byte_fallback {
        fields.push(("byte_fallback", Value::Bool(true)));
    }
    if let Some(u) = t.unk {
        fields.push(("unk", Value::U(u as u64)));
    }
    if !t.post_single.is_empty() {
        fields.push((
            "postprocessor",
            Value::map(vec![(
                "single",
                Value::Array(
                    t.post_single
                        .iter()
                        .map(|s| Value::text(s.clone()))
                        .collect(),
                ),
            )]),
        ));
    }
    Value::map(fields)
}

// ------------------------------------------------------------------ import --

/// The chat template out of `tokenizer_config.json`, translated to OMNI-CT.
///
/// A refusal is not a failure of the import: §06.9's whole argument is that a
/// template which cannot be expressed totally should not be shipped as
/// something a runtime executes. So the template is left out, and the
/// constructs that blocked it are named.
fn chat_template(b: &mut ModelBuilder, cfg: &json::Value, notes: &mut Vec<Note>) -> Option<Value> {
    let raw = match cfg.get("chat_template") {
        Some(json::Value::Str(s)) => s.clone(),
        // Newer configs carry a list of named templates; `default` is the one a
        // chat runtime uses.
        Some(json::Value::Array(a)) => {
            let pick = a
                .iter()
                .find(|e| e.get("name").and_then(|x| x.as_str()) == Some("default"))
                .or_else(|| a.first())?;
            pick.get("template").and_then(|x| x.as_str())?.to_string()
        }
        _ => return None,
    };
    let translated = match crate::jinja::translate(&raw) {
        Ok(t) => t,
        Err(crate::jinja::Error::Unsupported(r)) => {
            notes.push(Note {
                item: "chat_template".into(),
                reason: format!("Jinja2 `{}` — {}", r.construct, r.reason),
                action: "no chat template written; §06.9 will not ship a template it \
                         cannot express totally"
                    .into(),
            });
            return None;
        }
        Err(e) => {
            notes.push(Note {
                item: "chat_template".into(),
                reason: format!("the Jinja2 source did not parse: {e}"),
                action: "no chat template written".into(),
            });
            return None;
        }
    };
    // `translate` returns an already-parsed OMNI-CT template; its `source` is
    // the OMNI-CT the reviewer will read, not the Jinja that came in.
    let parsed = translated.template;
    for r in &translated.rewrites {
        notes.push(Note {
            item: "chat_template".into(),
            reason: format!("Jinja2 `{r}`"),
            action: "rewritten into OMNI-CT".into(),
        });
    }
    let ast = Object::blob(parsed.to_value().encode());
    let ast_digest = ast.digest(b.hash);
    b.extra_objects.push(ast);
    Some(Value::map(vec![
        ("t", Value::text("omni.tok/chat-template")),
        ("v", Value::U(1)),
        ("lang", Value::text(crate::ct::LANG)),
        ("source", Value::text(parsed.source.clone())),
        (
            "compiled",
            Value::Array(vec![Value::U(0), Value::Bytes(ast_digest.to_vec())]),
        ),
    ]))
}

/// Imports a Hugging Face model directory.
pub fn import(files: &Files, opts: &ImportOpts) -> Res<Imported> {
    if files.shards.is_empty() {
        return Err(Error::Missing(
            "no weights: expected model.safetensors, a *.index.json naming shards, or \
             pytorch_model*.bin"
                .into(),
        ));
    }

    let mut report = Fidelity {
        format: "hf-repo",
        importer: IMPORTER,
        source_path: opts.source_path.clone(),
        source_size: files.shards.iter().map(|s| s.bytes.len() as u64).sum(),
        lossless: true,
        represented: vec!["tensors".into(), "dtypes".into(), "shapes".into()],
        ..Default::default()
    };
    // I6: the digest of a *directory* is the digest of what was read from it,
    // in the order it was read, so the answer to "which files did this come
    // from" is one value rather than a list.
    let mut acc = Vec::new();
    for s in &files.shards {
        acc.extend_from_slice(s.name.as_bytes());
        acc.extend_from_slice(&opts.hash.digest(&s.bytes));
    }
    for (label, f) in [
        ("config.json", &files.config),
        ("tokenizer.json", &files.tokenizer),
        ("tokenizer_config.json", &files.tokenizer_config),
        ("generation_config.json", &files.generation_config),
    ] {
        if let Some(bytes) = f {
            acc.extend_from_slice(label.as_bytes());
            acc.extend_from_slice(&opts.hash.digest(bytes));
        }
    }
    report.source_digest = opts.hash.domain_digest("omni/hf-repo", &acc);

    let mut notes: Vec<Note> = Vec::new();
    let mut b = ModelBuilder::new(opts.name.clone())
        .hash(opts.hash)
        .chunk_size(opts.chunk_size);
    if let Some(spdx) = &opts.license {
        b = b.license(spdx.clone());
    }

    // --- weights -----------------------------------------------------------
    let mut tensors = 0usize;
    let mut bytes_in = 0u64;
    for shard in &files.shards {
        match shard.kind {
            Weights::Safetensors => {
                let f = crate::safetensors::File::parse(&shard.bytes)
                    .map_err(|e| Error::Malformed(format!("{}: {e}", shard.name)))?;
                for e in &f.entries {
                    b = b.tensor(crate::model::TensorSpec {
                        name: e.name.clone(),
                        shape: e.shape.clone(),
                        dtype: e.dtype.clone(),
                        axes: None,
                        semantic: "",
                        data: f.tensor(e).to_vec(),
                        layout: Some(crate::safetensors::layout_of(&e.dtype)),
                    });
                    tensors += 1;
                    bytes_in += e.len();
                }
            }
            Weights::PyTorch => {
                let out = crate::pytorch::import(
                    &shard.bytes,
                    &crate::safetensors::ImportOpts {
                        name: opts.name.clone(),
                        source_path: shard.name.clone(),
                        hash: opts.hash,
                        chunk_size: opts.chunk_size,
                        license: None,
                        arch: None,
                    },
                )
                .map_err(|e| Error::Malformed(format!("{}: {e}", shard.name)))?;
                // The PyTorch importer already verified every tensor against
                // the source; what is wanted here is its tensors, so they are
                // read back out of the graph it built.
                let (specs, n, nb) = respec(&out)?;
                for note in out.report.unrepresented {
                    report.lossless = false;
                    notes.push(note);
                }
                for s in specs {
                    b = b.tensor(s);
                }
                tensors += n;
                bytes_in += nb;
                report.represented.push("strides".into());
            }
        }
    }
    report.verified_tensors = tensors;
    report.verified_bytes = bytes_in;
    report.verify_method = "per-format importer";

    // --- architecture ------------------------------------------------------
    match &files.config {
        Some(raw) => {
            let cfg =
                json::parse(raw).map_err(|e| Error::Malformed(format!("config.json: {e}")))?;
            let (family, params) = arch_of(&cfg, &mut notes);
            b = b.arch(
                family.clone(),
                params
                    .iter()
                    .map(|(k, v)| (k.as_str(), v.clone()))
                    .collect(),
            );
            report.represented.push(format!("arch.family `{family}`"));
        }
        None => notes.push(Note {
            item: "arch".into(),
            reason: "no config.json in the directory".into(),
            action: "no architecture written; the tensor names are a convention, not a \
                     declaration"
                .into(),
        }),
    }

    // --- tokenizer ---------------------------------------------------------
    if let Some(raw) = &files.tokenizer {
        let tj = json::parse(raw).map_err(|e| Error::Malformed(format!("tokenizer.json: {e}")))?;
        let parts = tokenizer_of(&tj, &mut notes)?;
        report.represented.push(format!(
            "tokenizer ({}, {} tokens)",
            parts.kind,
            parts.tokens.len()
        ));
        let asset = tokenizer_asset(&mut b, &parts);
        b = b.asset("tokenizer", otype::TOKENIZER, asset);
        // §06.7.1. Vectors must come from the source tokenizer, and this
        // importer cannot run one; a vector produced by the encoder it tests
        // cannot fail, so none are written.
        notes.push(Note {
            item: "tokenizer conformance vectors (§06.7.1)".into(),
            reason: "vectors have to come from the source tokenizer, and this importer \
                     does not run `tokenizers`"
                .into(),
            action: "none written; generate them with the source library and attach with \
                     `omni pack`"
                .into(),
        });
    } else {
        notes.push(Note {
            item: "tokenizer".into(),
            reason: "no tokenizer.json in the directory".into(),
            action: "none written".into(),
        });
    }

    // --- chat template -----------------------------------------------------
    if let Some(raw) = &files.tokenizer_config {
        let tc = json::parse(raw)
            .map_err(|e| Error::Malformed(format!("tokenizer_config.json: {e}")))?;
        if let Some(asset) = chat_template(&mut b, &tc, &mut notes) {
            report.represented.push("chat_template (OMNI-CT)".into());
            b = b.asset("chat_template", otype::CHAT_TEMPLATE, asset);
        }
    }

    // --- generation defaults ----------------------------------------------
    if let Some(raw) = &files.generation_config {
        let g = json::parse(raw)
            .map_err(|e| Error::Malformed(format!("generation_config.json: {e}")))?;
        if let json::Value::Object(m) = &g {
            let pairs: Vec<(&str, Value)> =
                m.iter().map(|(k, v)| (k.as_str(), to_cbor(v))).collect();
            if !pairs.is_empty() {
                b = b.manifest_key("generation", Value::map(pairs));
                report.represented.push("generation defaults".into());
            }
        }
    }

    report.assumptions.extend(
        notes
            .iter()
            .filter(|n| n.action.starts_with("written") || n.action.starts_with("rewritten"))
            .cloned(),
    );
    report.unrepresented.extend(
        notes
            .into_iter()
            .filter(|n| !(n.action.starts_with("written") || n.action.starts_with("rewritten"))),
    );
    report.assumptions.push(Note {
        item: "license".into(),
        reason: "config.json declares none; a repo's LICENSE file is prose".into(),
        action: match &opts.license {
            Some(spdx) => format!("supplied by the caller as `{spdx}`"),
            None => "field omitted".into(),
        },
    });

    b = b.asset("provenance", otype::PROVENANCE, report.to_value());
    let (objects, root) = b.build();
    Ok(Imported {
        objects,
        root,
        report,
    })
}

/// Reads a PyTorch import's tensors back out of the graph it built, so they can
/// go into the combined model beside the rest of the repo.
fn respec(out: &Imported) -> Res<(Vec<crate::model::TensorSpec>, usize, u64)> {
    use crate::store::{MemoryStore, Store, WritableStore};
    let mut store = MemoryStore::new(crate::container::HashAlgo::default());
    for o in &out.objects {
        let _ = WritableStore::put(&mut store, &o.payload);
    }
    let ctx = crate::expr::Ctx::new(&store);
    let manifest = crate::cbor::decode(
        &Store::resolve(&store, &out.root)
            .map_err(|e| Error::Core(e.to_string()))?
            .ok_or_else(|| Error::Core("the built manifest is missing".into()))?,
    )
    .map_err(|e| Error::Core(e.to_string()))?;
    let model_ref = manifest
        .get("assets")
        .and_then(|a| a.get("model"))
        .and_then(|v| crate::expr::parse_ref_value(v).ok())
        .ok_or_else(|| Error::Core("no model asset".into()))?;
    let model = ctx
        .value(&model_ref.1)
        .map_err(|e| Error::Core(e.to_string()))?;
    let tt = model
        .get("tensors")
        .and_then(|v| crate::expr::parse_ref_value(v).ok())
        .ok_or_else(|| Error::Core("no tensor table".into()))?;
    let table =
        crate::tensor::TensorTable::load(&ctx, &tt).map_err(|e| Error::Core(e.to_string()))?;

    let mut specs = Vec::new();
    let mut bytes = 0u64;
    for name in table.load_order() {
        let r = table
            .get(name)
            .ok_or_else(|| Error::Core("a name vanished".into()))?;
        let desc =
            crate::tensor::TensorDesc::load(&ctx, r).map_err(|e| Error::Core(e.to_string()))?;
        let crate::expr::Expr::Literal { chunks, .. } = &desc.value else {
            return Err(Error::Core(format!("`{name}` is not a literal")));
        };
        let data = ctx
            .chunk_bytes(chunks)
            .map_err(|e| Error::Core(e.to_string()))?;
        bytes += data.len() as u64;
        specs.push(crate::model::TensorSpec {
            name: name.clone(),
            shape: desc.sizes().unwrap_or_default(),
            dtype: desc.dtype.clone(),
            axes: None,
            semantic: "",
            data,
            layout: Some(desc.layout.clone()),
        });
    }
    let n = specs.len();
    Ok((specs, n, bytes))
}

// ------------------------------------------------------------------- tests --

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> Vec<u8> {
        br#"{"model_type":"llama","hidden_size":8,"num_hidden_layers":2,
             "num_attention_heads":4,"num_key_value_heads":2,"intermediate_size":16,
             "vocab_size":9,"max_position_embeddings":128,"rms_norm_eps":1e-5,
             "rope_theta":10000.0,"tie_word_embeddings":false,
             "torch_dtype":"bfloat16","transformers_version":"4.44.0"}"#
            .to_vec()
    }

    fn tokenizer_json() -> Vec<u8> {
        br#"{"version":"1.0",
            "added_tokens":[{"id":0,"content":"<unk>","special":true,
                             "lstrip":false,"rstrip":false}],
            "normalizer":{"type":"Sequence","normalizers":[{"type":"NFC"},
                          {"type":"Lowercase"}]},
            "pre_tokenizer":{"type":"ByteLevel","add_prefix_space":true},
            "post_processor":{"type":"TemplateProcessing",
              "single":[{"SpecialToken":{"id":"<unk>","type_id":0}},
                        {"Sequence":{"id":"A","type_id":0}}]},
            "decoder":{"type":"ByteLevel"},
            "model":{"type":"BPE","unk_token":"<unk>","byte_fallback":true,
              "vocab":{"<unk>":0,"a":1,"b":2,"c":3,"ab":4,"abc":5,
                       "d":6,"e":7,"de":8},
              "merges":["a b","ab c","d e"]}}"#
            .to_vec()
    }

    fn safetensors_shard(names: &[&str]) -> Vec<u8> {
        let mut header = String::from("{");
        let mut data = Vec::new();
        for (i, n) in names.iter().enumerate() {
            let payload: Vec<u8> = (0..8u16)
                .flat_map(|x| (x + i as u16).to_le_bytes())
                .collect();
            if i > 0 {
                header.push(',');
            }
            header.push_str(&format!(
                "\"{n}\":{{\"dtype\":\"BF16\",\"shape\":[2,4],\"data_offsets\":[{},{}]}}",
                data.len(),
                data.len() + payload.len()
            ));
            data.extend_from_slice(&payload);
        }
        header.push('}');
        let h = header.into_bytes();
        let mut out = (h.len() as u64).to_le_bytes().to_vec();
        out.extend_from_slice(&h);
        out.extend_from_slice(&data);
        out
    }

    fn files() -> Files {
        Files {
            config: Some(cfg()),
            tokenizer: Some(tokenizer_json()),
            tokenizer_config: Some(
                br#"{"chat_template":"{% for m in messages %}<|{{ m.role }}|>{{ m.content }}{% endfor %}",
                     "bos_token":"<unk>"}"#
                    .to_vec(),
            ),
            generation_config: Some(br#"{"temperature":0.7,"top_p":0.9,"max_new_tokens":64}"#.to_vec()),
            shards: vec![Shard {
                name: "model.safetensors".into(),
                kind: Weights::Safetensors,
                bytes: safetensors_shard(&["model.embed_tokens.weight", "lm_head.weight"]),
            }],
        }
    }

    #[test]
    fn a_repo_becomes_one_container_with_all_five_files_in_it() {
        let out = import(&files(), &ImportOpts::default()).expect("imports");
        let r = &out.report;
        assert_eq!(r.verified_tensors, 2);
        assert!(
            r.represented
                .iter()
                .any(|s| s.contains("arch.family `llama`")),
            "{:?}",
            r.represented
        );
        assert!(
            r.represented
                .iter()
                .any(|s| s.starts_with("tokenizer (bpe, 9 tokens)")),
            "{:?}",
            r.represented
        );
        assert!(
            r.represented.iter().any(|s| s.contains("chat_template")),
            "{:?}",
            r.represented
        );
        assert!(
            r.represented.iter().any(|s| s.contains("generation")),
            "{:?}",
            r.represented
        );
    }

    #[test]
    fn the_config_maps_onto_06_2_and_keeps_the_rest_under_its_own_name() {
        let mut notes = Vec::new();
        let parsed = json::parse(&cfg()).expect("parses");
        let (family, params) = arch_of(&parsed, &mut notes);
        assert_eq!(family, "llama");
        let get = |k: &str| params.iter().find(|(n, _)| n == k).map(|(_, v)| v.clone());
        assert_eq!(get("n_layers"), Some(Value::U(2)));
        assert_eq!(get("n_kv_heads"), Some(Value::U(2)));
        assert_eq!(get("ffn_hidden"), Some(Value::U(16)));
        // §06.3's interleaved is written from knowledge of the implementation,
        // and the report says so.
        let rope = get("rope").expect("a rope block");
        assert_eq!(rope.get("interleaved"), Some(&Value::Bool(false)));
        assert!(notes.iter().any(|n| n.item == "rope.interleaved"));
        // The norm block comes from a key HF spells three different ways.
        assert_eq!(
            get("norm").and_then(|n| n.get("kind").cloned()),
            Some(Value::text("rmsnorm"))
        );
        // And nothing is dropped: `torch_dtype` was not mapped, so it is kept.
        let hf = get("hf").expect("the untouched keys");
        assert_eq!(hf.get("torch_dtype"), Some(&Value::text("bfloat16")));
    }

    #[test]
    fn an_unknown_family_gets_no_rope_block_rather_than_a_guessed_one() {
        let raw = br#"{"model_type":"some-new-thing","rope_theta":10000.0}"#;
        let mut notes = Vec::new();
        let (family, params) = arch_of(&json::parse(raw).expect("parses"), &mut notes);
        assert_eq!(family, "some-new-thing");
        assert!(params.iter().all(|(k, _)| k != "rope"));
        assert!(notes
            .iter()
            .any(|n| n.reason.contains("§06.3 requires `interleaved`")));
        // …and `rope_theta` survives under `hf`, so the value is not lost.
        let hf = params.iter().find(|(k, _)| k == "hf").expect("hf keys");
        assert!(hf.1.get("rope_theta").is_some());
    }

    #[test]
    fn merges_become_id_pairs_and_a_merge_naming_nothing_is_an_error() {
        let mut notes = Vec::new();
        let tj = json::parse(&tokenizer_json()).expect("parses");
        let t = tokenizer_of(&tj, &mut notes).expect("reads");
        assert_eq!(t.kind, "bpe");
        assert_eq!(t.tokens.len(), 9);
        // "a b" -> (1, 2); "ab c" -> (4, 3); "d e" -> (6, 7).
        assert_eq!(t.merges, vec![(1, 2), (4, 3), (6, 7)]);
        assert_eq!(t.unk, Some(0));
        assert!(t.byte_fallback);
        assert_eq!(t.post_single, vec!["<unk>".to_string(), "A".to_string()]);

        let bad = br#"{"model":{"type":"BPE","vocab":{"a":0,"b":1},"merges":["a z"]}}"#;
        let err = tokenizer_of(&json::parse(bad).expect("parses"), &mut notes)
            .map(|_| ())
            .expect_err("z is not in the vocabulary");
        assert!(err.to_string().contains("does not contain"), "{err}");
    }

    #[test]
    fn a_vocabulary_with_a_hole_in_it_is_an_error() {
        // A gap means the two halves of the file disagree, and every id past
        // the gap would be wrong.
        let raw = br#"{"model":{"type":"BPE","vocab":{"a":0,"b":2}}}"#;
        let mut notes = Vec::new();
        let err = tokenizer_of(&json::parse(raw).expect("parses"), &mut notes)
            .map(|_| ())
            .expect_err("id 1 is missing");
        assert!(err.to_string().contains("skips id 1"), "{err}");
    }

    #[test]
    fn a_step_outside_06_7s_catalogue_is_carried_by_name_not_dropped() {
        let raw = br#"{"normalizer":{"type":"NFKC"},
                       "pre_tokenizer":{"type":"Digits","individual_digits":true},
                       "model":{"type":"BPE","vocab":{"a":0}}}"#;
        let mut notes = Vec::new();
        let t = tokenizer_of(&json::parse(raw).expect("parses"), &mut notes).expect("reads");
        assert_eq!(
            t.normalizers[0].get("k").and_then(|x| x.as_str()),
            Some("nfkc")
        );
        assert_eq!(
            t.pretokenizers[0].get("k").and_then(|x| x.as_str()),
            Some("digits")
        );
        assert!(notes.iter().any(|n| n.item == "normalizer `nfkc`"));
        assert!(notes.iter().any(|n| n.item == "pre-tokenizer `digits`"));
    }

    #[test]
    fn a_unigram_tokenizer_keeps_its_scores() {
        let raw = br#"{"model":{"type":"Unigram","unk_id":0,
                       "vocab":[["<unk>",0.0],["\u2581a",-2.5],["b",-3.25]]}}"#;
        let mut notes = Vec::new();
        let t = tokenizer_of(&json::parse(raw).expect("parses"), &mut notes).expect("reads");
        assert_eq!(t.kind, "unigram");
        assert_eq!(t.scores, vec![0.0, -2.5, -3.25]);
        assert_eq!(t.unk, Some(0));
    }

    #[test]
    fn a_tokenizer_model_06_7_has_no_entry_for_is_refused_by_name() {
        let raw = br#"{"model":{"type":"SentencePieceBPEWithMagic","vocab":{}}}"#;
        let mut notes = Vec::new();
        let err = tokenizer_of(&json::parse(raw).expect("parses"), &mut notes)
            .map(|_| ())
            .expect_err("not a catalogued model");
        assert!(
            err.to_string().contains("SentencePieceBPEWithMagic"),
            "{err}"
        );
        assert!(err.to_string().contains("change every id"), "{err}");
    }

    #[test]
    fn the_imported_tokenizer_reads_back_and_encodes() {
        let out = import(&files(), &ImportOpts::default()).expect("imports");
        let packed = crate::container::pack(
            &out.objects,
            &out.root,
            &crate::container::PackOptions::default(),
        )
        .expect("packs");
        let c = crate::container::Container::open(packed).expect("opens");
        let store = crate::store::Borrowed(&c);
        let ctx = crate::expr::Ctx::new(&store);
        let manifest = c.root().expect("root");
        let tr = crate::expr::parse_ref_value(
            manifest
                .get("assets")
                .and_then(|a| a.get("tokenizer"))
                .expect("a tokenizer asset"),
        )
        .expect("ref");
        let tok = crate::tokenizer::Tokenizer::load(&ctx, &tr).expect("loads");
        assert_eq!(tok.vocab_size(), 9);
        assert_eq!(tok.merges.len(), 3);
        // The two normalizers this build does implement, in order.
        assert_eq!(tok.normalizers.len(), 2);
        assert!(tok.unsupported().is_empty(), "{:?}", tok.unsupported());
    }

    #[test]
    fn a_jinja_template_it_cannot_translate_is_left_out_and_named() {
        let mut f = files();
        // `loop.index` is one of §06.9's known gaps.
        f.tokenizer_config = Some(
            br#"{"chat_template":"{% for m in messages %}{{ loop.index }}{% endfor %}"}"#.to_vec(),
        );
        let out = import(&f, &ImportOpts::default()).expect("imports anyway");
        assert!(!out
            .report
            .represented
            .iter()
            .any(|s| s.contains("chat_template")));
        assert!(
            out.report
                .unrepresented
                .iter()
                .any(|n| n.item == "chat_template" && n.reason.contains("loop")),
            "{:?}",
            out.report.unrepresented
        );
    }

    #[test]
    fn a_repo_with_no_weights_is_refused_with_what_it_looked_for() {
        let f = Files {
            config: Some(cfg()),
            ..Default::default()
        };
        let err = import(&f, &ImportOpts::default())
            .map(|_| ())
            .expect_err("no weights");
        assert!(err.to_string().contains("model.safetensors"), "{err}");
    }

    #[test]
    fn sharded_weights_land_in_one_model_in_the_order_they_were_given() {
        let mut f = files();
        f.shards = vec![
            Shard {
                name: "model-00001-of-00002.safetensors".into(),
                kind: Weights::Safetensors,
                bytes: safetensors_shard(&["model.embed_tokens.weight"]),
            },
            Shard {
                name: "model-00002-of-00002.safetensors".into(),
                kind: Weights::Safetensors,
                bytes: safetensors_shard(&["lm_head.weight"]),
            },
        ];
        let out = import(&f, &ImportOpts::default()).expect("imports");
        assert_eq!(out.report.verified_tensors, 2);
        // The source digest covers both shards *and* their names, so two repos
        // whose shards differ only in how they were cut do not collide.
        let mut g = f;
        g.shards.swap(0, 1);
        let other = import(&g, &ImportOpts::default()).expect("imports");
        assert_ne!(out.report.source_digest, other.report.source_digest);
    }

    #[test]
    fn the_conformance_vector_gap_is_reported_rather_than_papered_over() {
        let out = import(&files(), &ImportOpts::default()).expect("imports");
        assert!(out
            .report
            .unrepresented
            .iter()
            .any(|n| n.item.contains("conformance vectors")));
    }
}
