#!/usr/bin/env python3
"""The Gate 1 and Gate 2 measurements, over whatever corpus you point them at.

Both gates ask for numbers this repository cannot produce on its own, and the
distinction is worth being exact about. Gate 1 wants a lossless round trip
"verified bit-exactly on ≥ 100 real models" and "a published delta-size study
over ≥ 50 real base/fine-tune pairs". Gate 2 wants "tokenizer vectors pass for
≥ 200 real tokenizers" and "Jinja2 → OMNI-CT translation for ≥ 95 % of chat
templates on a public hub snapshot". None of those is blocked on code. All four
are blocked on a corpus.

This is the instrument. Point it at a directory of real models and it produces
the measurement the gate asks for, with the denominator stated, so what remains
between this repository and those rows is downloading the models rather than
writing anything.

    tools/corpus.py roundtrip  <dir>   [--omni ./omni] [--json out.json]
    tools/corpus.py delta      <pairs> [--omni ./omni] [--json out.json]
    tools/corpus.py tokenizers <dir>   [--omni ./omni] [--json out.json]
    tools/corpus.py templates  <dir>   [--omni ./omni] [--json out.json]

`roundtrip` walks a directory of models — `.safetensors`, `.gguf`, `.onnx`, or a
Hugging Face repo directory — imports each, exports it back, and compares the
result with the source **byte for byte**. That is the strongest reading of
"lossless" and the one Gate 1 uses; a run reports how many models met it, how
many were refused with a reason, and how many failed.

`delta` takes a file of `base<TAB>tuned` container paths, one pair per line,
runs `omni delta` over each, and reports the delta as a percentage of the base.
The study Gate 1 asks for is that table plus its distribution.

`tokenizers` walks a directory of `tokenizer.json` files and reports how many
import into a §06.7 tokenizer this build can *encode* with, naming the
normalizer or pre-tokenizer that blocked each one that did not. Note what this
does **not** measure: §06.7.1 conformance vectors have to come from the source
tokenizer, and a vector generated by the encoder it is meant to test cannot
fail. If a corpus supplies vectors beside a tokenizer as `<name>.vectors.json`,
they are run; where it does not, the run says so rather than counting a
tokenizer as passing something nobody checked.

`templates` runs `omni jinja --coverage` over a directory of chat templates.

Every subcommand prints the gate's own threshold next to the figure and exits
non-zero when the figure is short of it, so a corpus run is a check rather than
a report somebody has to read.
"""

import json
import os
import pathlib
import shutil
import statistics
import subprocess
import sys
import tempfile

# What `roundtrip` knows how to import, and the verb it uses. The order matters
# only for a repo directory, which is recognised by its files rather than by an
# extension.
FORMATS = [
    (".safetensors", "safetensors"),
    (".gguf", "gguf"),
    (".onnx", "onnx"),
    (".bin", "pytorch"),
]


def run(omni, args, **kw):
    """One CLI call, with the output kept whatever the exit status."""
    p = subprocess.run([omni, *args], capture_output=True, text=True, **kw)
    return p.returncode, p.stdout + p.stderr


def find_models(root):
    """Every model under `root`, as `(path, format)`."""
    out = []
    for dirpath, dirnames, files in os.walk(root):
        d = pathlib.Path(dirpath)
        # A Hugging Face repo is a directory, not a file: it is the five files
        # together that mean something (`import-export.md` §4.1), so it is
        # imported whole and its parts are not imported again.
        if "config.json" in files and any(
            f.endswith(".safetensors") or f.endswith(".bin") for f in files
        ):
            out.append((d, "hf"))
            dirnames[:] = []
            continue
        for f in sorted(files):
            for ext, fmt in FORMATS:
                if f.endswith(ext):
                    out.append((d / f, fmt))
                    break
    return out


def roundtrip(omni, root, report):
    """Gate 1: import → export → compare, bit for bit."""
    models = find_models(root)
    if not models:
        print(f"{root}: no models found")
        return 1
    exact, refused, failed = [], [], []
    tmp = tempfile.mkdtemp(prefix="omni-corpus-")
    try:
        for i, (path, fmt) in enumerate(models):
            name = str(path)
            container = os.path.join(tmp, f"m{i}.omni")
            code, out = run(omni, ["import", fmt, name, "-o", container])
            if code != 0:
                # Exit 4 is a refusal with a reason — a format feature this
                # build will not guess at — and that is a different outcome
                # from a failure. Gate 1 counts them apart.
                (refused if code == 4 else failed).append(
                    {"model": name, "format": fmt, "stage": "import", "why": out.strip()}
                )
                continue
            if fmt in ("hf", "pytorch"):
                # No exporter, by design: §12.10 clause 4 for pickle, and a repo
                # is a bundle rather than a file. Counted as refused with the
                # reason rather than silently skipped.
                refused.append(
                    {
                        "model": name,
                        "format": fmt,
                        "stage": "export",
                        "why": "no exporter for this format",
                    }
                )
                continue
            back = os.path.join(tmp, f"m{i}.back")
            code, out = run(
                omni, ["export", fmt, container, "-o", back, "--allow-lossy"]
            )
            if code != 0:
                (refused if code == 4 else failed).append(
                    {"model": name, "format": fmt, "stage": "export", "why": out.strip()}
                )
                continue
            a = pathlib.Path(name).read_bytes()
            b = pathlib.Path(back).read_bytes()
            if a == b:
                exact.append({"model": name, "format": fmt, "bytes": len(a)})
            else:
                failed.append(
                    {
                        "model": name,
                        "format": fmt,
                        "stage": "compare",
                        "why": f"{len(a)} bytes in, {len(b)} out",
                    }
                )
            print(f"  {'✓' if a == b else '✗'} {name}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    total = len(models)
    print(
        f"\n{root}: {len(exact)} of {total} round-trip byte for byte "
        f"({100.0 * len(exact) / total:.1f} %)"
    )
    print(f"  refused with a reason  {len(refused)}")
    print(f"  failed                 {len(failed)}")
    for f in failed:
        print(f"    ✗ {f['model']} ({f['stage']}): {f['why'].splitlines()[0]}")
    print(
        "\nGate 1 asks for a lossless round trip verified bit-exactly on ≥ 100 "
        f"real models. This run saw {total}."
    )
    write(report, {"gate": 1, "measure": "roundtrip", "corpus": str(root),
                   "models": total, "exact": exact, "refused": refused,
                   "failed": failed})
    # Short of the gate's count, or anything actually failed.
    return 0 if (len(exact) >= 100 and not failed) else 3


def delta(omni, pairs_file, report):
    """Gate 1: the delta-size study."""
    pairs = []
    for line in open(pairs_file):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t") if "\t" in line else line.split()
        if len(parts) != 2:
            print(f"  ✗ not a `base<TAB>tuned` pair: {line}")
            return 2
        pairs.append(parts)
    if not pairs:
        print(f"{pairs_file}: no pairs")
        return 1

    rows, failed = [], []
    tmp = tempfile.mkdtemp(prefix="omni-delta-")
    try:
        for i, (base, tuned) in enumerate(pairs):
            out = os.path.join(tmp, f"d{i}.omni")
            code, log = run(omni, ["delta", base, tuned, "-o", out])
            if code != 0:
                failed.append({"base": base, "tuned": tuned, "why": log.strip()})
                print(f"  ✗ {base} → {tuned}")
                continue
            b = os.path.getsize(base)
            d = os.path.getsize(out)
            rows.append(
                {"base": base, "tuned": tuned, "base_bytes": b, "delta_bytes": d,
                 "percent": 100.0 * d / max(b, 1)}
            )
            print(f"  ✓ {base} → {tuned}: {100.0 * d / max(b, 1):.2f} % of base")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if rows:
        pcts = sorted(r["percent"] for r in rows)
        print(
            f"\n{len(rows)} pair(s): median {statistics.median(pcts):.2f} %, "
            f"min {pcts[0]:.2f} %, max {pcts[-1]:.2f} %"
        )
    print(f"  failed  {len(failed)}")
    print(
        "\nGate 1 asks for a published delta-size study over ≥ 50 real "
        f"base/fine-tune pairs. This run saw {len(pairs)}."
    )
    write(report, {"gate": 1, "measure": "delta", "pairs": len(pairs),
                   "rows": rows, "failed": failed})
    return 0 if (len(rows) >= 50 and not failed) else 3


def tokenizers(omni, root, report):
    """Gate 2: how many real tokenizers this build can encode with."""
    files = sorted(
        p for p in pathlib.Path(root).rglob("tokenizer.json") if p.is_file()
    )
    if not files:
        print(f"{root}: no tokenizer.json found")
        return 1
    ok, blocked, failed, vectors_run = [], [], [], 0
    tmp = tempfile.mkdtemp(prefix="omni-tok-")
    try:
        for i, path in enumerate(files):
            # A tokenizer travels with its model, so the repo importer is what
            # reads it — the same path a real import takes.
            repo = path.parent
            container = os.path.join(tmp, f"t{i}.omni")
            code, out = run(omni, ["import", "hf", str(repo), "-o", container])
            if code != 0:
                (blocked if code == 4 else failed).append(
                    {"tokenizer": str(path), "why": out.strip()}
                )
                print(f"  ✗ {path}")
                continue
            # `verify --tokenizer` runs whatever §06.7.1 vectors the container
            # carries. An import that wrote none says *indeterminate*, which is
            # the honest answer and not a pass.
            code, out = run(omni, ["verify", container, "--tokenizer"])
            if code == 0:
                vectors_run += 1
                ok.append({"tokenizer": str(path), "vectors": True})
            elif "unsupported" in out or "indeterminate" in out.lower():
                ok.append({"tokenizer": str(path), "vectors": False,
                           "note": out.strip().splitlines()[-1] if out.strip() else ""})
            else:
                failed.append({"tokenizer": str(path), "why": out.strip()})
            print(f"  ✓ {path}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    total = len(files)
    print(
        f"\n{root}: {len(ok)} of {total} imported as a §06.7 tokenizer "
        f"({100.0 * len(ok) / total:.1f} %)"
    )
    print(f"  with conformance vectors  {vectors_run}")
    print(f"  refused with a reason     {len(blocked)}")
    print(f"  failed                    {len(failed)}")
    print(
        "\nGate 2 asks that tokenizer vectors pass for ≥ 200 real tokenizers. "
        f"This run imported {len(ok)} and ran vectors for {vectors_run} — and "
        "the second number is the one the gate means. Vectors have to come from "
        "the source tokenizer: one generated by the encoder it is meant to test "
        "cannot fail."
    )
    write(report, {"gate": 2, "measure": "tokenizers", "corpus": str(root),
                   "found": total, "imported": ok, "blocked": blocked,
                   "failed": failed, "vectors_run": vectors_run})
    return 0 if (vectors_run >= 200 and not failed) else 3


def templates(omni, root, report):
    """Gate 2: Jinja2 → OMNI-CT over a corpus of chat templates."""
    code, out = run(omni, ["jinja", "--coverage", str(root)])
    print(out.rstrip())
    write(report, {"gate": 2, "measure": "templates", "corpus": str(root),
                   "exit": code, "output": out})
    return code


def write(path, obj):
    if path:
        pathlib.Path(path).write_text(json.dumps(obj, indent=2))
        print(f"\nwrote {path}")


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 2
    cmd, target = argv[1], argv[2]
    rest = argv[3:]
    omni = "./omni"
    report = None
    for i, a in enumerate(rest):
        if a == "--omni" and i + 1 < len(rest):
            omni = rest[i + 1]
        if a == "--json" and i + 1 < len(rest):
            report = rest[i + 1]
    fn = {
        "roundtrip": roundtrip,
        "delta": delta,
        "tokenizers": tokenizers,
        "templates": templates,
    }.get(cmd)
    if fn is None:
        print(f"unknown measurement `{cmd}`")
        return 2
    return fn(omni, target, report)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
