#!/usr/bin/env python3
"""Build a tokenizer and its §06.7.1 conformance vectors with the real library.

`tools/corpus.py tokenizers` has always reported two numbers apart: how many
tokenizers imported, and how many ran *vectors*. The second was always zero, and
the reason was sound — §06.7.1 vectors have to come from the source tokenizer,
because a vector generated by the encoder it is meant to test cannot fail — but
it meant the measurement Gate 2 asks for had never been taken. `omni verify
--tokenizer` was checking nothing, and would have passed for an encoder that was
wrong.

This closes it from the other side. It trains a tokenizer with Hugging Face
`tokenizers`, writes the `tokenizer.json` that library produces, and writes the
ids *that library* assigns as `tokenizer_vectors.tsv`. The importer carries the
file into the container, and `verify --tokenizer` then compares OMNI's encoder
against a tokenizer it shares no code with.

    tools/tokenizer-vectors.py <out-dir> [--kind bpe|wordpiece] [--vectors N]

The vectors are the deliverable, not the tokenizer. A wrong OMNI encoder now
fails; before this, nothing here could have told you.
"""

import argparse
import json
import os
import struct
import sys

# Enough text to train a small but real vocabulary. Deliberately mixed: repeated
# subwords so merges are interesting, punctuation the pre-tokenizer must split,
# digits, casing, and a couple of non-ASCII words so byte handling is exercised.
CORPUS = [
    "a model exists once and everything else is derived",
    "models model modelling modelled modeller remodel",
    "tokenize tokenizer tokenizing tokenized tokenization",
    "the quick brown fox jumps over the lazy dog",
    "hashing, chunking; addressing: content-addressed storage",
    "0 1 2 3 42 1024 65536 8380417",
    "Uppercase MiXeD lowercase UPPER",
    "naïve café résumé Zürich",
    "compress decompress recompress compressible",
    "verify verified verifying verification verifier",
]

PROBES = [
    "a model exists once",
    "tokenizer",
    "remodelling the models",
    "content-addressed",
    "Zürich café",
    "42 1024",
    "unseenwordxyz",
    "the the the",
    "MiXeD case",
    "verify verification",
]


def build(kind, out, n_vectors):
    from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders

    if kind == "bpe":
        tok = Tokenizer(models.BPE(unk_token="<unk>"))
        tok.pre_tokenizer = pre_tokenizers.Whitespace()
        trainer = trainers.BpeTrainer(vocab_size=300, special_tokens=["<unk>"],
                                      show_progress=False)
    elif kind == "wordpiece":
        tok = Tokenizer(models.WordPiece(unk_token="<unk>"))
        tok.pre_tokenizer = pre_tokenizers.Whitespace()
        tok.decoder = decoders.WordPiece()
        trainer = trainers.WordPieceTrainer(vocab_size=300,
                                           special_tokens=["<unk>"],
                                           show_progress=False)
    else:
        raise SystemExit(f"unknown kind {kind}")

    tok.train_from_iterator(CORPUS, trainer)
    os.makedirs(out, exist_ok=True)
    tok.save(os.path.join(out, "tokenizer.json"))

    probes = (PROBES * ((n_vectors // len(PROBES)) + 1))[:n_vectors]
    lines = [
        "# §06.7.1 conformance vectors.",
        f"# Produced by huggingface `tokenizers` ({kind}), not by OMNI. That is the",
        "# whole point: a vector generated by the encoder it tests cannot fail.",
    ]
    for text in probes:
        ids = tok.encode(text).ids
        # The format `omni verify --tokenizer` reads: the text, a tab, then the
        # ids. A tab or newline in the text would break it, so those are refused
        # here rather than written and misread later.
        if "\t" in text or "\n" in text:
            raise SystemExit(f"a probe contains a tab or newline: {text!r}")
        lines.append(f"{text}\t{','.join(str(i) for i in ids)}")
    with open(os.path.join(out, "tokenizer_vectors.tsv"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    vocab = tok.get_vocab()
    # A minimal model beside it, because a tokenizer travels with one and the
    # repo importer is the path that reads it.
    json.dump({"model_type": "llama", "hidden_size": 8, "num_hidden_layers": 1},
              open(os.path.join(out, "config.json"), "w"))
    hdr = json.dumps({"w": {"dtype": "F32", "shape": [2, 2],
                            "data_offsets": [0, 16]}},
                     separators=(",", ":")).encode()
    with open(os.path.join(out, "model.safetensors"), "wb") as f:
        f.write(struct.pack("<Q", len(hdr)) + hdr + b"\0" * 16)

    print(f"{out}: {kind}, {len(vocab)} tokens, {len(probes)} vectors from "
          f"tokenizers")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--kind", default="bpe", choices=["bpe", "wordpiece"])
    ap.add_argument("--vectors", type=int, default=10)
    a = ap.parse_args()
    try:
        import tokenizers  # noqa: F401
    except ImportError:
        print("needs the `tokenizers` package", file=sys.stderr)
        return 2
    return build(a.kind, a.out, a.vectors)


if __name__ == "__main__":
    sys.exit(main())
